// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrlKPWvG3gKtYH1y7jzEK9vuA-6E_dTU',
    appId: '1:1000930116471:web:f6c3b246a84e020c6ed772',
    messagingSenderId: '1000930116471',
    projectId: 'facial-recognition-syste-c82ae',
    authDomain: 'facial-recognition-syste-c82ae.firebaseapp.com',
    storageBucket: 'facial-recognition-syste-c82ae.appspot.com',
    measurementId: 'G-63VNBLRWC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18Ku4XldR4x_hwdbR2QFawRIOO9Wt8WM',
    appId: '1:1000930116471:android:d64cd5b5aaf13cf06ed772',
    messagingSenderId: '1000930116471',
    projectId: 'facial-recognition-syste-c82ae',
    storageBucket: 'facial-recognition-syste-c82ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7bRFQQJ6ejrxhaqZaQtmXiJrbpBLAGI',
    appId: '1:1000930116471:ios:bc6fb714ddd846896ed772',
    messagingSenderId: '1000930116471',
    projectId: 'facial-recognition-syste-c82ae',
    storageBucket: 'facial-recognition-syste-c82ae.appspot.com',
    iosClientId: '1000930116471-t1dhpap9l9r20at9jc474hc91ouragt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileUi',
  );
}
